### ISSUE TITLE
Centralizar localización colombiana

### ISSUE THREAD

**Issue by grottas** [ccamargov/TRM-Col-Odoo#1]
Hola @ccamargov 

Le interesaría centralizar el trabajo comunitario para la localización colombiana en https://github.com/odooloco/l10n-colombia ?

Saludos

**Comment by ccamargov** [comment]
Hola @grottas ,

Claro que si, con gusto... Que métodología de integración están utilizando en ese repositorio?

**Comment by grottas** [comment]
@ccamargov La idea es ajustarnos a los lineamientos de OCA. Podemos abrir la discusión en el repositorio a ver qué dicen las personas que ya están ahí, y se le va dando una forma más organizada de trabajo.

**Comment by ccamargov** [comment]
@grottas Genial, quedaría atento a sus instrucciones para iniciar el proceso.

**Comment by grottas** [comment]
@ccamargov Si te parece, haces fork del repositorio https://github.com/odooloco/l10n-colombia , pones ahí tu trabajo y le haces un PR.

Dale una revisada a ver si puedes actualizarlo a la nueva API, y revisa esto:

https://www.npmjs.com/package/trmcol

Saludos,

**Comment by grottas** [comment]
En el repositorio también hay un PR y varios módulos para que les des una mirada

https://github.com/odooloco/l10n-colombia/pull/1
